### ISSUE TITLE
数据可以发一下吗？学生做论文用

### ISSUE THREAD

**Issue by grantsimongrant** [TRHX/Python3-Spider-Practice#1]
914322592@qq.com，如果能帮忙，十分感谢！

**Comment by TRHX** [comment]
哪个数据？

**Comment by gumpsimon** [comment]
51job的招聘数据&nbsp;


甘校玲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ITBOB • ***@***.***&gt;; 
发送时间: 2021年10月12日(星期二) 上午9:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TRHX/Python3-Spider-Practice] 数据可以发一下吗？学生做论文用 (#1)





 
哪个数据？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
